import type { InspiringPerson } from "./types";

export const people: InspiringPerson[] = [
  {
    name: "Marie Curie",
    quote: "Nothing in life is to be feared, it is only to be understood.",
    blurb: "Pioneering physicist and chemist who was the first woman to win a Nobel Prize and the only person to win Nobel Prizes in two different sciences.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Marie_Curie_c._1920s.jpg/220px-Marie_Curie_c._1920s.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Marie_Curie" }],
    tags: ["science", "physics", "chemistry"],
  },
  {
    name: "Ada Lovelace",
    quote: "That brain of mine is something more than merely mortal, as time will show.",
    blurb: "English mathematician recognized as the first computer programmer for her work on Charles Babbage's Analytical Engine.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Ada_Lovelace_portrait.jpg/220px-Ada_Lovelace_portrait.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ada_Lovelace" }],
    tags: ["science", "mathematics", "computing"],
  },
  {
    name: "Srinivasa Ramanujan",
    quote: "An equation for me has no meaning unless it expresses a thought of God.",
    blurb: "Indian mathematician who made extraordinary contributions to mathematical analysis, number theory, and continued fractions with almost no formal training.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Srinivasa_Ramanujan_-_OPC_-_1.jpg/220px-Srinivasa_Ramanujan_-_OPC_-_1.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Srinivasa_Ramanujan" }],
    tags: ["science", "mathematics"],
  },
  {
    name: "Richard Feynman",
    quote: "The first principle is that you must not fool yourself — and you are the easiest person to fool.",
    blurb: "American theoretical physicist known for his work in quantum electrodynamics, particle physics, and his exceptional gift for teaching.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Richard_Feynman_Nobel.jpg/220px-Richard_Feynman_Nobel.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Richard_Feynman" }],
    tags: ["science", "physics"],
  },
  {
    name: "Rosalind Franklin",
    quote: "Science and everyday life cannot and should not be separated.",
    blurb: "English chemist and X-ray crystallographer whose work was central to understanding the molecular structures of DNA, RNA, and viruses.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rosalind_Franklin" }],
    tags: ["science", "chemistry"],
  },
  {
    name: "Albert Einstein",
    quote: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
    blurb: "German-born theoretical physicist who developed the theory of relativity, one of the two pillars of modern physics.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Albert_Einstein_Head.jpg/220px-Albert_Einstein_Head.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Albert_Einstein" }],
    tags: ["science", "physics"],
  },
  {
    name: "Nikola Tesla",
    quote: "The present is theirs; the future, for which I really worked, is mine.",
    blurb: "Serbian-American inventor and engineer best known for his contributions to the design of the modern alternating current electricity supply system.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/N.Tesla.JPG/220px-N.Tesla.JPG",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Nikola_Tesla" }],
    tags: ["science", "engineering", "tech"],
  },
  {
    name: "Jane Goodall",
    quote: "What you do makes a difference, and you have to decide what kind of difference you want to make.",
    blurb: "English primatologist and anthropologist who transformed our understanding of chimpanzees and became a global advocate for conservation.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Jane_Goodall_2015.jpg/220px-Jane_Goodall_2015.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Jane_Goodall" }],
    tags: ["science", "activism", "conservation"],
  },
  {
    name: "Carl Sagan",
    quote: "Somewhere, something incredible is waiting to be known.",
    blurb: "American astronomer, cosmologist, and science communicator who popularized astronomy and inspired a generation to look skyward.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Carl_Sagan_Planetary_Society.JPG/220px-Carl_Sagan_Planetary_Society.JPG",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Carl_Sagan" }],
    tags: ["science", "astronomy"],
  },
  {
    name: "Emmy Noether",
    quote: "My methods are really methods of working and thinking; this is why they have crept in everywhere anonymously.",
    blurb: "German mathematician who made groundbreaking contributions to abstract algebra and theoretical physics, including Noether's theorem.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Noether.jpg/220px-Noether.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Emmy_Noether" }],
    tags: ["science", "mathematics"],
  },
  {
    name: "Frida Kahlo",
    quote: "I paint flowers so they will not die.",
    blurb: "Mexican painter known for her vivid, deeply personal self-portraits and works inspired by Mexican folk art that explored identity, pain, and the human body.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg/220px-Frida_Kahlo%2C_by_Guillermo_Kahlo.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Frida_Kahlo" }],
    tags: ["art"],
  },
  {
    name: "Ludwig van Beethoven",
    quote: "Music is a higher revelation than all wisdom and philosophy.",
    blurb: "German composer and pianist whose works bridged the Classical and Romantic periods and remain among the most performed in the concert repertoire.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Beethoven.jpg/220px-Beethoven.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ludwig_van_Beethoven" }],
    tags: ["art", "music"],
  },
  {
    name: "Maya Angelou",
    quote: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.",
    blurb: "American poet, memoirist, and civil rights activist whose works explored themes of identity, family, and racism.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Angelou_at_Clinton_inauguration_%28cropped_2%29.jpg/220px-Angelou_at_Clinton_inauguration_%28cropped_2%29.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Maya_Angelou" }],
    tags: ["art", "literature", "activism"],
  },
  {
    name: "Yayoi Kusama",
    quote: "Our earth is only one polka dot among a million stars in the cosmos.",
    blurb: "Japanese contemporary artist who works across painting, sculpture, film, and immersive installations, known for her polka dots and infinity rooms.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Yayoi_Kusama" }],
    tags: ["art"],
  },
  {
    name: "Leonardo da Vinci",
    quote: "Learning never exhausts the mind.",
    blurb: "Italian polymath of the Renaissance whose areas of interest included painting, sculpting, architecture, science, music, mathematics, and engineering.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Francesco_Melzi_-_Portrait_of_Leonardo.png/220px-Francesco_Melzi_-_Portrait_of_Leonardo.png",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Leonardo_da_Vinci" }],
    tags: ["art", "science", "engineering"],
  },
  {
    name: "Nina Simone",
    quote: "You have to learn to get up from the table when love is no longer being served.",
    blurb: "American singer, songwriter, and civil rights activist whose music spanned classical, jazz, blues, folk, R&B, gospel, and pop.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Nina_Simone" }],
    tags: ["art", "music", "activism"],
  },
  {
    name: "Pablo Picasso",
    quote: "Every child is an artist. The problem is how to remain an artist once we grow up.",
    blurb: "Spanish painter, sculptor, and ceramicist who co-founded Cubism and is widely regarded as one of the most influential artists of the 20th century.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Pablo_picasso_1.jpg/220px-Pablo_picasso_1.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Pablo_Picasso" }],
    tags: ["art"],
  },
  {
    name: "Johann Sebastian Bach",
    quote: "The aim and final end of all music should be none other than the glory of God and the refreshment of the soul.",
    blurb: "German composer and musician of the Baroque period, regarded as one of the greatest composers in the history of Western music.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Johann_Sebastian_Bach.jpg/220px-Johann_Sebastian_Bach.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Johann_Sebastian_Bach" }],
    tags: ["art", "music"],
  },
  {
    name: "Martin Luther King Jr.",
    quote: "Darkness cannot drive out darkness; only light can do that. Hate cannot drive out hate; only love can do that.",
    blurb: "American Baptist minister and activist who was the most visible spokesperson and leader in the American civil rights movement.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Martin_Luther_King%2C_Jr..jpg/220px-Martin_Luther_King%2C_Jr..jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Martin_Luther_King_Jr." }],
    tags: ["activism", "civil rights"],
  },
  {
    name: "Malala Yousafzai",
    quote: "One child, one teacher, one book, one pen can change the world.",
    blurb: "Pakistani activist for female education and the youngest Nobel Prize laureate, known for her advocacy of girls' right to education.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Malala_Yousafzai_at_Girl_Summit_2014.jpg/220px-Malala_Yousafzai_at_Girl_Summit_2014.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Malala_Yousafzai" }],
    tags: ["activism", "education"],
  },
  {
    name: "Nelson Mandela",
    quote: "It always seems impossible until it's done.",
    blurb: "South African anti-apartheid revolutionary and political leader who served as President of South Africa from 1994 to 1999.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Nelson_Mandela_1994.jpg/220px-Nelson_Mandela_1994.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Nelson_Mandela" }],
    tags: ["activism", "civil rights", "leadership"],
  },
  {
    name: "Rosa Parks",
    quote: "I have learned over the years that when one's mind is made up, this diminishes fear.",
    blurb: "American activist in the civil rights movement, best known for her pivotal role in the Montgomery bus boycott.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Rosa_Parks_%28National_Archives_and_Records_Administration%2C_306-PS-26-2380%29_%28cropped%29.jpg/220px-Rosa_Parks.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rosa_Parks" }],
    tags: ["activism", "civil rights"],
  },
  {
    name: "Frederick Douglass",
    quote: "Once you learn to read, you will be forever free.",
    blurb: "American social reformer, abolitionist, orator, writer, and statesman who became a leader of the abolitionist movement after escaping from slavery.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Frederick_Douglass_portrait.jpg/220px-Frederick_Douglass_portrait.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Frederick_Douglass" }],
    tags: ["activism", "civil rights", "literature"],
  },
  {
    name: "Mahatma Gandhi",
    quote: "Be the change that you wish to see in the world.",
    blurb: "Indian lawyer and anti-colonial nationalist who employed nonviolent resistance to lead India's independence movement against British rule.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Mahatma-Gandhi%2C_studio%2C_1931.jpg/220px-Mahatma-Gandhi%2C_studio%2C_1931.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Mahatma_Gandhi" }],
    tags: ["activism", "leadership"],
  },
  {
    name: "Harriet Tubman",
    quote: "Every great dream begins with a dreamer.",
    blurb: "American abolitionist and political activist who rescued dozens of enslaved people through the Underground Railroad.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Harriet_Tubman_c1868-69_%28cropped%29.jpg/220px-Harriet_Tubman_c1868-69_%28cropped%29.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Harriet_Tubman" }],
    tags: ["activism", "civil rights"],
  },
  {
    name: "Desmond Tutu",
    quote: "Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.",
    blurb: "South African Anglican cleric and theologian who was a leading figure in the anti-apartheid movement and won the Nobel Peace Prize in 1984.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Desmond_Tutu" }],
    tags: ["activism", "civil rights"],
  },
  {
    name: "Alan Turing",
    quote: "We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    blurb: "English mathematician and computer scientist who is widely considered the father of theoretical computer science and artificial intelligence.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Alan_Turing_Aged_16.jpg/220px-Alan_Turing_Aged_16.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Alan_Turing" }],
    tags: ["tech", "computing", "mathematics"],
  },
  {
    name: "Grace Hopper",
    quote: "The most dangerous phrase in the language is 'We've always done it this way.'",
    blurb: "American computer scientist and United States Navy rear admiral who was a pioneer of computer programming and invented one of the first linkers.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg/220px-Commodore_Grace_M._Hopper%2C_USN_%28covered%29.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Grace_Hopper" }],
    tags: ["tech", "computing"],
  },
  {
    name: "Tim Berners-Lee",
    quote: "The Web as I envisaged it, we have not seen it yet. The future is still so much bigger than the past.",
    blurb: "English computer scientist best known as the inventor of the World Wide Web, fundamentally changing how information is shared globally.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Sir_Tim_Berners-Lee_%28cropped%29.jpg/220px-Sir_Tim_Berners-Lee_%28cropped%29.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Tim_Berners-Lee" }],
    tags: ["tech", "computing"],
  },
  {
    name: "Linus Torvalds",
    quote: "Talk is cheap. Show me the code.",
    blurb: "Finnish-American software engineer who created the Linux kernel and the version control system Git, both cornerstones of modern software.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/LinuxCon_Europe_Linus_Torvalds_03_%28cropped%29.jpg/220px-LinuxCon_Europe_Linus_Torvalds_03_%28cropped%29.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Linus_Torvalds" }],
    tags: ["tech", "computing"],
  },
  {
    name: "Margaret Hamilton",
    quote: "There was no choice but to be pioneers.",
    blurb: "American computer scientist and systems engineer who led the team that developed the on-board flight software for NASA's Apollo missions.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Margaret_Hamilton_1995.jpg/220px-Margaret_Hamilton_1995.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Margaret_Hamilton_(software_engineer)" }],
    tags: ["tech", "computing", "science"],
  },
  {
    name: "Katherine Johnson",
    quote: "I counted everything. I counted the steps to the road, the steps up to church, the number of dishes and silverware I washed.",
    blurb: "American mathematician whose calculations of orbital mechanics at NASA were critical to the success of the first crewed spaceflights.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Katherine_Johnson_at_NASA%2C_in_1966.jpg/220px-Katherine_Johnson_at_NASA%2C_in_1966.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Katherine_Johnson" }],
    tags: ["tech", "science", "mathematics"],
  },
  {
    name: "Simone de Beauvoir",
    quote: "One is not born, but rather becomes, a woman.",
    blurb: "French existentialist philosopher, writer, and feminist activist whose work laid the foundation for the modern feminist movement.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Simone_de_Beauvoir" }],
    tags: ["philosophy", "literature", "activism"],
  },
  {
    name: "Marcus Aurelius",
    quote: "The happiness of your life depends upon the quality of your thoughts.",
    blurb: "Roman emperor and Stoic philosopher whose personal writings, known as Meditations, remain a cornerstone of Western philosophy.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/MSR-ra-61-b-1-DM.jpg/220px-MSR-ra-61-b-1-DM.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Marcus_Aurelius" }],
    tags: ["philosophy", "leadership"],
  },
  {
    name: "Confucius",
    quote: "It does not matter how slowly you go as long as you do not stop.",
    blurb: "Chinese philosopher and politician whose teachings on ethics, morality, and governance profoundly shaped East Asian thought and culture.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Confucius_Tang_Dynasty.jpg/220px-Confucius_Tang_Dynasty.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Confucius" }],
    tags: ["philosophy"],
  },
  {
    name: "Socrates",
    quote: "The unexamined life is not worth living.",
    blurb: "Classical Greek philosopher credited as one of the founders of Western philosophy, known for the Socratic method of questioning.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Socrate_du_Louvre.jpg/220px-Socrate_du_Louvre.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Socrates" }],
    tags: ["philosophy"],
  },
  {
    name: "Hannah Arendt",
    quote: "The sad truth is that most evil is done by people who never make up their minds to be good or evil.",
    blurb: "German-American political theorist whose work dealt with the nature of power, politics, authority, and totalitarianism.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hannah_Arendt" }],
    tags: ["philosophy", "politics"],
  },
  {
    name: "Lao Tzu",
    quote: "A journey of a thousand miles begins with a single step.",
    blurb: "Ancient Chinese philosopher and writer, traditionally regarded as the founder of Taoism and the author of the Tao Te Ching.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Laozi" }],
    tags: ["philosophy"],
  },
  {
    name: "Toni Morrison",
    quote: "If there's a book that you want to read, but it hasn't been written yet, then you must write it.",
    blurb: "American novelist and Nobel Prize laureate whose works explored African American identity and history with lyrical, powerful prose.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Toni_Morrison_2008-2.jpg/220px-Toni_Morrison_2008-2.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Toni_Morrison" }],
    tags: ["literature"],
  },
  {
    name: "Rumi",
    quote: "The wound is the place where the Light enters you.",
    blurb: "13th-century Persian poet and Sufi mystic whose works on love, spirituality, and the human condition transcend cultural boundaries.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rumi" }],
    tags: ["literature", "philosophy"],
  },
  {
    name: "James Baldwin",
    quote: "Not everything that is faced can be changed, but nothing can be changed until it is faced.",
    blurb: "American writer and activist whose essays, novels, and plays explored race, sexuality, and class in mid-20th-century America.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/James_Baldwin" }],
    tags: ["literature", "activism"],
  },
  {
    name: "Ursula K. Le Guin",
    quote: "We live in capitalism. Its power seems inescapable. So did the divine right of kings.",
    blurb: "American author best known for her works of speculative fiction, including the Earthsea series and The Left Hand of Darkness.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Ursula_K._Le_Guin" }],
    tags: ["literature"],
  },
  {
    name: "Virginia Woolf",
    quote: "You cannot find peace by avoiding life.",
    blurb: "English writer considered one of the most important modernist 20th-century authors and a pioneer in the use of stream of consciousness.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg/220px-George_Charles_Beresford_-_Virginia_Woolf_in_1902_-_Restoration.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Virginia_Woolf" }],
    tags: ["literature"],
  },
  {
    name: "Jorge Luis Borges",
    quote: "I have always imagined that Paradise will be a kind of library.",
    blurb: "Argentine short-story writer, essayist, and poet whose work embraced the labyrinth, infinity, and the blurring of reality and fiction.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Jorge_Luis_Borges" }],
    tags: ["literature"],
  },
  {
    name: "Amelia Earhart",
    quote: "The most effective way to do it is to do it.",
    blurb: "American aviation pioneer and author who was the first female aviator to fly solo across the Atlantic Ocean.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Amelia_Earhart_standing_under_nose_of_her_Lockheed_Model_10-E_Electra%2C_small.jpg/220px-Amelia_Earhart.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Amelia_Earhart" }],
    tags: ["exploration", "aviation"],
  },
  {
    name: "Wangari Maathai",
    quote: "It's the little things citizens do. That's what will make the difference. My little thing is planting trees.",
    blurb: "Kenyan social, environmental, and political activist who founded the Green Belt Movement and became the first African woman to win the Nobel Peace Prize.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Wangari_Maathai_portrait_by_Martin_Rowe.jpg/220px-Wangari_Maathai_portrait_by_Martin_Rowe.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Wangari_Maathai" }],
    tags: ["activism", "environment"],
  },
  {
    name: "Tu Youyou",
    quote: "Every scientist dreams of doing something that can help the world.",
    blurb: "Chinese pharmaceutical chemist who discovered artemisinin, a treatment for malaria that has saved millions of lives, winning the Nobel Prize in 2015.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Tu_Youyou" }],
    tags: ["science", "medicine"],
  },
  {
    name: "Stephen Hawking",
    quote: "However difficult life may seem, there is always something you can do and succeed at.",
    blurb: "English theoretical physicist and cosmologist whose work on black holes and relativity made him one of the most celebrated scientists of the modern era.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Stephen_Hawking.StarChild.jpg/220px-Stephen_Hawking.StarChild.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Stephen_Hawking" }],
    tags: ["science", "physics"],
  },
  {
    name: "Rachel Carson",
    quote: "In every walk with nature, one receives far more than he seeks.",
    blurb: "American marine biologist and conservationist whose book Silent Spring advanced the global environmental movement.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Rachel-Carson.jpg/220px-Rachel-Carson.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rachel_Carson" }],
    tags: ["science", "activism", "environment"],
  },
  {
    name: "W.E.B. Du Bois",
    quote: "The cost of liberty is less than the price of repression.",
    blurb: "American sociologist, historian, and civil rights activist who co-founded the NAACP and was a leading voice for racial equality.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/W._E._B._Du_Bois" }],
    tags: ["activism", "civil rights", "literature"],
  },
  {
    name: "Hypatia",
    quote: "Reserve your right to think, for even to think wrongly is better than not to think at all.",
    blurb: "Alexandrian mathematician, astronomer, and philosopher who was one of the last great thinkers of ancient Alexandria.",
    imageUrl: "",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hypatia" }],
    tags: ["science", "mathematics", "philosophy"],
  },
  {
    name: "Rabindranath Tagore",
    quote: "You can't cross the sea merely by standing and staring at the water.",
    blurb: "Bengali polymath who was the first non-European to win the Nobel Prize in Literature, reshaping Bengali literature and music.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Rabindranath_Tagore_in_1909.jpg/220px-Rabindranath_Tagore_in_1909.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Rabindranath_Tagore" }],
    tags: ["literature", "art", "philosophy"],
  },
  {
    name: "Hedy Lamarr",
    quote: "All creative people want to do the unexpected.",
    blurb: "Austrian-American actress and inventor who co-invented an early technique for spread spectrum communications, a key technology behind Wi-Fi and Bluetooth.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Hedy_Lamarr_Algiers_2.jpg/220px-Hedy_Lamarr_Algiers_2.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Hedy_Lamarr" }],
    tags: ["tech", "art"],
  },
  {
    name: "Mae Jemison",
    quote: "Never limit yourself because of others' limited imagination.",
    blurb: "American engineer, physician, and NASA astronaut who became the first African American woman to travel into space.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mae_C._Jemison%2C_MD.jpg/220px-Mae_C._Jemison%2C_MD.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Mae_Jemison" }],
    tags: ["science", "exploration"],
  },
  {
    name: "Charles Darwin",
    quote: "It is not the strongest of the species that survives, nor the most intelligent, but the one most responsive to change.",
    blurb: "English naturalist, geologist, and biologist best known for his contributions to evolutionary biology and the theory of natural selection.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Charles_Darwin_seated_crop.jpg/220px-Charles_Darwin_seated_crop.jpg",
    links: [{ label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Charles_Darwin" }],
    tags: ["science"],
  },
];
